export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_DELETE_ITEM = "CART_DELETE_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const CART_SAVE_SAHIPPING_ADDRESS = "CART_SAVE_SAHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
